### ISSUE TITLE
PA Review: New Account Creation, Login, Demo/Guest Login

### ISSUE THREAD

**Issue by sperrow** [sperrow/90s-genius#7]

**Comment by LochandQuay** [comment]
@sperrow 

Functionality Issues:
- [x] Should clear form errors if closing modal. Especially if switching between form types
- [x] Prefer to have a way to toggle between the two forms ("Already have an account? Sign In"/"Don't have an account? Sign Up")

Styling Issues:
- [x] Would prefer if errors stood out more
- [x] Needs more styling on the session forms in general. 
    - [x] More whitespace between internal elements; you have a large session form box and the elements are bunched up in the corner
    - [x] input fields could be larger, and they should have some kind of alignment (centered or otherwise)
